In [5]:
import numpy as np

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.


In [8]:
arr1d=np.arange(30)
arr2d=arr1d.reshape(15,2)
arr2d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [15]:
arr1d= np.random.randint(0,600,60,dtype=int)
arr1d= arr1d.reshape(2,5,-1)
arr1d

array([[[ 48,  30, 159,  46, 173,  78],
        [189, 464, 197, 567, 190,  20],
        [118, 252,   5, 112, 364, 598],
        [224, 470, 214,  36,  28, 170],
        [  7, 153, 292, 114,  14, 306]],

       [[292, 163,  93, 259, 487, 529],
        [260, 549, 162, 105, 288, 159],
        [172, 445, 149, 206, 573, 202],
        [563, 179, 384, 168,  92, 234],
        [115, 212, 388,  64, 362, 376]]])

3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [26]:
arr2d=np.random.randint(0,9,20).reshape(4,5)
arr1d=arr2d.reshape(-1)
arr1d




array([1, 1, 5, 8, 3, 3, 7, 3, 0, 2, 7, 7, 4, 0, 1, 8, 6, 7, 8, 7])

In [27]:
arr1d.ndim

1

In [28]:
arr1d.shape

(20,)

4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.


In [33]:
arr2d = np.array([[1,2,3],[5,8,4]])
for i in arr2d:
  for x in i:
    print(x)


1
2
3
5
8
4


In [35]:
for x in np.nditer(arr2d):
  print(x)
     

1
2
3
5
8
4


5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [36]:
arr1=np.arange(5,31,5)
arr2=np.arange(1,7)
arr1+arr2

array([ 6, 12, 18, 24, 30, 36])

In [37]:
arr1*arr2

array([  5,  20,  45,  80, 125, 180])

In [38]:
arr1-arr2

array([ 4,  8, 12, 16, 20, 24])

In [39]:
arr1/arr2

array([5., 5., 5., 5., 5., 5.])

6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.


In [40]:
arr2d=np.random.randint(0,100,10)
arr2d



array([ 5, 79, 67, 62,  8,  2, 84, 81, 13, 82])

In [41]:
arr2d.mean()


48.3

In [42]:
arr2d.sum()



483

In [43]:
arr2d.var()


1184.81

In [44]:
arr2d.std()


34.421069129241175

7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.


In [47]:
arr1=np.arange(0,20)
arr2=np.arange(500,531)
np.concatenate([arr1,arr2] , axis = 0 )

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.


In [49]:
arr1=np.arange(15,51)
arr2=np.arange(10,101)
arr3= np.concatenate([arr1,arr2] , axis = 0 )
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [50]:
arr3[25:51] = 888
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [54]:
arr1=np.arange(0,40).reshape(8,5)
arr2=np.arange(320,360).reshape(8,5)
arr3= np.concatenate([arr1,arr2] , axis = 0 )
arr3

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [55]:
arr4= np.concatenate([arr1,arr2] , axis = 1 )
arr4

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.


In [ ]:
arr1.reshape(4,2,5)
arr2.reshape(2,4,5)
arr6 = np.concatenate([arr1,arr2] , axis = 2 )
arr6


#  concatenate ve stack işleminde belirtilen axis satır ve sutunlardan birleştirme işlemi yapar 0 satırda  1 ise sutundan birleştrir bu yüzden axis = 2 geçersiz bir değerdir  

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.


In [68]:
arr1d = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(arr1d == 5 )

(array([ 5, 13]),)

12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.


In [73]:
arr1d = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(arr1d%2==0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.


In [75]:
np.where(arr1d>4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.


In [76]:
np.where(arr1d%5==0)

(array([ 1,  2,  5, 13]),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin


In [77]:
np.random.randint(85,101)

85

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.


In [79]:
np.random.randint(10,100,9).reshape(3,3)

array([[10, 80, 18],
       [91, 68, 47],
       [34, 66, 34]])

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.


In [85]:
arr = np.arange(35,60)
np.random.choice(arr)

42

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [89]:
arr2d=np.array([3,8,10,53]).reshape(2,2)
arr2d
#4 elemanlı bir arrayda (2,5) matrisinde bir shape oluşturulamaz. Bunun için 10 eleman gereklidir.

array([[ 3,  8],
       [10, 53]])